Add diagrams
discreetlogcontracts/dlcspecs pull request #151
Opened 2021-03-02 23:31 UTC by matthewjablack

This PR adds diagrams showing an overview of on-chain and off-chain transactions involved with entering and exiting a DLC. 

It also includes a fee-bumping diagram and depiction of participant/outsider view of a DLC from a block explorer. 

Thanks to @Abhimanyu1994 for putting these together 🙏 🔥 

![dlc_overview](https://user-images.githubusercontent.com/5362629/109728821-f0283b00-7b84-11eb-8ad0-81ba4f7877e7.png)

![dlc_overview_rbf](https://user-images.githubusercontent.com/5362629/109728831-f4545880-7b84-11eb-84bf-52978f2813ad.png)

![dlc_participant_view](https://user-images.githubusercontent.com/5362629/109728837-f74f4900-7b84-11eb-8c8e-994053f1484a.png)

![dlc_outsider_view](https://user-images.githubusercontent.com/5362629/109728842-fae2d000-7b84-11eb-807b-3d89a7726312.png)

2021-03-08 04:01 UTC, prayank23 requested changes
There is only one typo. Everything else looks good and will be helpful.

2021-03-08 04:01 UTC, ghost commented on Introduction.md
> +
There is a typo in this image. It should be `UTXOs` instead of `UXTOS`

2021-03-08 04:02 UTC, benthecarman commented on Introduction.md
> +
In `dlc_overview_rbf` as well

2021-03-08 16:04 UTC, matthewjablack commented on Introduction.md
> +
Good catch, updated

2021-03-08 16:15 UTC, prayank23 commented on Introduction.md
> +
It's still incorrect in `dlc_overview`. `X` is at wrong place. 

Incorrect: U**X**TOs
Correct: U**TX**Os

2021-03-08 17:02 UTC, matthewjablack commented on Introduction.md
> +
2nd time is the charm haha. Updated thanks

2021-03-30 19:17 UTC, nkohen commented on Introduction.md
> +![DLC Overview](/images/dlc_overview.png)
For me (locally, not on github) these images only get properly linked in without the `/` prefix which I don't think should be here (on all pic links)

2021-03-30 19:42 UTC, matthewjablack commented on Introduction.md
> +![DLC Overview](/images/dlc_overview.png)
Works either way for me so I'll switch to no `/` prefix.

2021-03-30 20:08 UTC, nkohen approved these changes

2021-03-30 20:09 UTC, merged