Move oracle related TLV info to Messaging.md
discreetlogcontracts/dlcspecs pull request #162
Opened 2021-04-13 05:13 UTC by Tibo-lg

The TOC of `Messaging.md` including some parts about oracle messages, but actually they were not there. As we discussed moving all TLV serialization info to Messaging I moved them there and updated the TOC.

2021-04-13 06:41 UTC, nkohen requested changes
Looks good but I think you need to modify the table of contents for both files moving the sections from one to the other

2021-04-13 06:53 UTC, Tibo-lg commented
> Looks good but I think you need to modify the table of contents for both files moving the sections from one to the other

Good point thanks updated.

2021-04-15 17:31 UTC, benthecarman approved these changes
ACK d7a58e540db40ee8e48f1cd42ee557ea7a4f23c5

2021-04-20 06:45 UTC, nkohen approved these changes

2021-04-20 06:52 UTC, merged